### ISSUE TITLE
Im getting this issue, please help!

### ISSUE THREAD

**Issue by fbbunn** [DaniEnsi/TikTok-Bot#1]
Traceback (most recent call last):
  File "C:\Users\fbbun\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1493, in _execute_child     
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TokViewV2\TokView V2.py", line 48, in __init__
    self.driver = webdriver.Chrome(options=options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\fbbun\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver
                                                                                       r\chrome\webdriver.py", line 70, in __init__
    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], "goog",  
  File "C:\Users\fbbun\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver
                                                                                       r\chromium\webdriver.py", line 90, in __init__
    self.service.start()
  File "C:\Users\fbbun\AppData\Roaming\Python\Python311\site-packages\selenium\webdriver
                                                                                       r\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs 
                                                                                        to be in PATH. Please see https://chromedriver.chromium.org/home

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\TokViewV2\TokView V2.py", line 278, in <module>
    obj = automator()
          ^^^^^^^^^^^
  File "C:\TokViewV2\TokView V2.py", line 50, in __init__
    self.error(f"Error trying to load web driver: {e}")
  File "C:\TokViewV2\TokView V2.py", line 233, in error
    self.driver.set_window_position(-10000, 0)
    ^^^^^^^^^^^
AttributeError: 'automator' object has no attribute 'driver'

**Comment by DaniEnsi** [comment]
Its seems like you do not have Chrome installed or added it to path... To fix this, just install or reinstall chrome
